### ISSUE TITLE
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by iteratelance** [Dwolla/dwolla-v2-python#21]
When running a long process it appears that the underlying request library throws an error.

### Sample code:
```python
        token = dwollav2.Client(
                key = self.app.config.get('DWOLLA_KEY'),
                secret = self.app.config.get('DWOLLA_SECRET'),
                environment = self.app.config.get('DWOLLA_ENV')
            ).Auth.client()
```
### The errors:
**ConnectionError**
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
requests/adapters.py in send at line 490
```python
                    # Then, reraise so that we can handle the actual exception.
                    low_conn.close()
                    raise
        except (ProtocolError, socket.error) as err:
            raise ConnectionError(err, request=request)
        except MaxRetryError as e:
            if isinstance(e.reason, ConnectTimeoutError):
                # TODO: Remove this in 3.0.0: see #2811
                if not isinstance(e.reason, NewConnectionError):
```
**ConnectionResetError**
[Errno 104] Connection reset by peer
python3.6/ssl.py in read at line 625
```
        If 'buffer' is provided, read into this buffer and return the number of
        bytes read.
        """
        if buffer is not None:
            v = self._sslobj.read(len, buffer)
        else:
            v = self._sslobj.read(len)
        return v
    def write(self, data):
```
From our logs it appears that the initial handshake makes a call to get an access_token and subsequent calls always create a new HTTPS connection for api.dwolla.com but not for the www.dwollo.com domain.

1. Request 
```
[DEBUG] Starting new HTTPS connection (1): www.dwolla.com
[DEBUG] https://www.dwolla.com:443 "POST /oauth/v2/token HTTP/1.1" 200 None
[DEBUG] Starting new HTTPS connection (1): api.dwolla.com
```

2. Request (several minutes later)
```
[DEBUG] https://www.dwolla.com:443 "POST /oauth/v2/token HTTP/1.1" 200 None
[DEBUG] Starting new HTTPS connection (1): api.dwolla.com
[DEBUG] https://api.dwolla.com:443 "GET /mass-payments/XXXXX/items HTTP/1.1" 200 2331
[DEBUG] https://www.dwolla.com:443 "POST /oauth/v2/token HTTP/1.1" 200 None
[DEBUG] Starting new HTTPS connection (1): api.dwolla.com
[DEBUG] https://api.dwolla.com:443 "GET /transfers/XXXXX HTTP/1.1" 200 1247
```
Notice there is no subsequent connection made for www.dwolla.com.  It appears www.dwolla.com, unlike api.dwolla.com becomes cached by the request library and eventually the connection drops raising an error.

Future logs, after a connection error, show the connection being reestablished as follows.  Note `(2): www.dwolla.com`.  Where (2) is the num of connections made to that host during a process.  I've noticed that after every error the connection count increases.

```
[DEBUG] Starting new HTTPS connection (2): www.dwolla.com
[DEBUG] https://www.dwolla.com:443 "POST /oauth/v2/token HTTP/1.1" 200 None
[DEBUG] Starting new HTTPS connection (1): api.dwolla.com
[DEBUG] https://api.dwolla.com:443 "GET /mass-payments/XXX/items HTTP/1.1" 200 
```
It seems that the issues would resolve if the library did not cache the www.dwolla.com host or a new connection was established per request.

As a work around I've tried to add a try catch block around the token code until I can come up with a better solution but have had mixed results thus far.

**Comment by iteratelance** [comment]
Suggestion, wrap session object inside of method rather than the module.  I believe that this would alleviate the problem.

```python
def _request_token(client, payload):
    session = requests.session()
    session.headers.update({'user-agent': 'dwolla-v2-python %s' % version})
    res = session.post(client.token_url, data=payload)
    if _is_error(res):
        raise Error.map(res)
    token = client.Token(res.json())
    if client.on_grant is not None:
        client.on_grant(token)
    return token
```
Current
```python
session = requests.session()
session.headers.update({'user-agent': 'dwolla-v2-python %s' % version})

def _request_token(client, payload):
    res = session.post(client.token_url, data=payload)
    if _is_error(res):
        raise Error.map(res)
    token = client.Token(res.json())
    if client.on_grant is not None:
        client.on_grant(token)
    return token

**Comment by sausman** [comment]
Hey @iteratelance, thanks for the detailed issue!

A while back we moved the session object to the module ([#8](https://github.com/Dwolla/dwolla-v2-python/pull/8)) to take advantage of [persistent connections and connection pooling](http://docs.python-requests.org/en/master/user/advanced/#session-objects). 

Requests to `www.dwolla.com` and `api.dwolla.com` are handled in a similar way. Requests to `www.dwolla.com` share a connection pool, whereas requests to `api.dwolla.com` share a connection pool per-Token.

Does this SO issue sound like it could be what's happening? https://stackoverflow.com/questions/383738/104-connection-reset-by-peer-socket-error-or-when-does-closing-a-socket-resu/35945309#35945309

**Comment by iteratelance** [comment]
@sausman Thanks for the reply.  I think it has something to do with AWS Lambda functions and how they operate.  I've ran into this issue in the past when running async and threaded http request on Lambda.  I'm not certain why connection polling has issues on Lambda, other than the underlying host might actually change from time to time, even using a stay warm long running process, thus breaking the connection.

In any event my final solution was to close the connection after getting each auth token.  This solved my issues.
```python
from dwollav2 import auth

def auth():
    client = dwollav2.Client(
            key = config.get('DWOLLA_KEY'),
            secret = config.get('DWOLLA_SECRET'),
            environment = config.get('DWOLLA_ENV')
        )

    application_token = client.Auth.client()
    auth.session.close()
    return application_token
