### ISSUE TITLE
Token URL Changes Not Released

### ISSUE THREAD

**Issue by kolanos** [Dwolla/dwolla-v2-python#26]
The changes slated for 2/11 have not been released for this client.

https://developers.dwolla.com/resources/changelog.html#changing

**Comment by kolanos** [comment]
Related: https://github.com/Dwolla/dwolla-v2-python/pull/22

**Comment by sausman** [comment]
Hey @kolanos,

Just to double check, are you using v1.3.0? https://pypi.org/project/dwollav2/#files

It looks to me like the token url change went out with v1.3.0.

**Comment by kolanos** [comment]
@sausman Yeah, I'm running v1.3.0 but am being told we're still hitting the old token URLs? Is there anything extra I need to do to ensure I'm using the correct URLs?

**Comment by kolanos** [comment]
Confirming this change was released and v1.3.0 is using correct URLs.
