### ISSUE TITLE
readme.md link to Integrations Authorization Guide is broken

### ISSUE THREAD

**Issue by MarieRobinson** [Dwolla/dwolla-v2-python#41]
line 51

Check out our [Integrations Authorization Guide](https://developers.dwolla.com/integrations/authorization).

this link returns 404 page not found

**Comment by tarricsookdeo** [comment]
Hi @MarieRobinson ! Thanks for bringing this to our attention. The features in the Integrations Authorization Guide have reached their end of support and have been deprecated, so the guide has been removed from the dev docs. I'll be removing the link to it in the README as well. Thanks again!
